<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit78309dcbeca0ebff7e667e61f2528422
{
    public static $files = array (
        '948ad5488880985ff1c06721a4e447fe' => __DIR__ . '/..' . '/cakephp/utility/bootstrap.php',
        '72142d7b40a3a0b14e91825290b5ad82' => __DIR__ . '/..' . '/cakephp/core/functions.php',
        '7b4ea634fa5bd1ccea7e5ca039562961' => __DIR__ . '/..' . '/colshrapnel/safemysql/safemysql.class.php',
    );

    public static $prefixLengthsPsr4 = array (
        'l' => 
        array (
            'la\\core\\' => 8,
        ),
        'f' => 
        array (
            'flow\\social\\' => 12,
            'flow\\' => 5,
        ),
        'P' => 
        array (
            'Psr\\SimpleCache\\' => 16,
        ),
        'C' => 
        array (
            'Cake\\Utility\\' => 13,
            'Cake\\Core\\' => 10,
            'Cake\\Cache\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'la\\core\\' => 
        array (
            0 => __DIR__ . '/..' . '/flowflow/core/src',
        ),
        'flow\\social\\' => 
        array (
            0 => __DIR__ . '/..' . '/flowflow/social/src/flow/social',
        ),
        'flow\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
        'Psr\\SimpleCache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'Cake\\Utility\\' => 
        array (
            0 => __DIR__ . '/..' . '/cakephp/utility',
        ),
        'Cake\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/cakephp/core',
        ),
        'Cake\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/cakephp/cache',
        ),
    );

    public static $prefixesPsr0 = array (
        'U' => 
        array (
            'Unirest\\' => 
            array (
                0 => __DIR__ . '/..' . '/mashape/unirest-php/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit78309dcbeca0ebff7e667e61f2528422::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit78309dcbeca0ebff7e667e61f2528422::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit78309dcbeca0ebff7e667e61f2528422::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit78309dcbeca0ebff7e667e61f2528422::$classMap;

        }, null, ClassLoader::class);
    }
}
