 jQuery(document).ready(function($) {
    var sourceIcons = {
        'Web Application' : ['icon-heart', 'icon-lemon'],
        'Accessibility' : [
            'icon-american-sign-language-interpreting', 
            'icon-assistive-listening-systems',
            'icon-audio-description',
            'icon-blind',
            'icon-braille',
            'icon-cc',
            'icon-asl-interpreting',
            'icon-low-vision',
            'icon-question-circle-o',
            'icon-sign-language',
            'icon-tty',
            'icon-universal-access',
            'icon-volume-control-phone',
            'icon-wheelchair',
            'icon-wheelchair-alt'
        ],
        'Weather' : [
            'icon-windy-rain-inv',
            'icon-snow-inv',
            'icon-snow-heavy-inv',
            'icon-hail-inv',
            'icon-clouds-inv',
            'icon-clouds-flash-inv',
            'icon-temperature',
            'icon-compass-1',
            'icon-na',
            'icon-celcius',
            'icon-fahrenheit',
            'icon-clouds-flash-alt',
            'icon-sun-inv',
            'icon-moon-inv',
            'icon-cloud-sun-inv',
            'icon-cloud-moon-inv',
            'icon-cloud-inv',
            'icon-cloud-flash-inv',
            'icon-drizzle-inv',
            'icon-rain-inv',
            'icon-windy-inv',
            'icon-sunrise',
            'icon-sun-1',
            'icon-moon-1',
            'icon-eclipse',
            'icon-mist',
            'icon-wind',
            'icon-snowflake',
            'icon-cloud-sun',
            'icon-cloud-moon',
            'icon-fog-sun',
            'icon-fog-moon',
            'icon-fog-cloud',
            'icon-fog',
            'icon-cloud-1',
            'icon-cloud-flash',
            'icon-cloud-flash-alt',
            'icon-drizzle',
            'icon-rain',
            'icon-windy',
            'icon-windy-rain',
            'icon-snow',
            'icon-snow-alt',
            'icon-snow-heavy',
            'icon-hail',
            'icon-clouds',
            'icon-clouds-flash',
            'icon-thermometer',
            'icon-thermometer-3',
            'icon-thermometer-2',
            'icon-thermometer-quarter',
            'icon-thermometer-0'
        ]
    }

        $('#myselect').fontIconPicker({
            source: sourceIcons,
            theme: 'fip-bootstrap',
            emptyIcon: false,
            hasSearch: true
        }); // Load with default options
    });